server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para API si quieres servir todo por el puerto 80 (opcional en K8s, usualmente se hace via Ingress)
    # location /api {
    #     proxy_pass http://backend:8080;
    # }
}
